# Generated by Django 3.1.1 on 2021-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dish_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='driver',
            new_name='rider',
        ),
    ]
