# Generated by Django 3.1.1 on 2021-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210513_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='defaultdish.png', upload_to=''),
        ),
    ]
