# Generated by Django 3.1.1 on 2021-07-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_restaurant_user'),
        ('system_supports', '0004_auto_20210527_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrestaurant',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='store.restaurant'),
        ),
    ]
