# Generated by Django 3.1.1 on 2021-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
