# Generated by Django 3.2.3 on 2021-05-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210510_0010'),
        ('store', '0006_restaurant'),
        ('system_supports', '0003_auto_20210415_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='profiles.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='store.restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='reportDoctor',
        ),
    ]
